gh tests artifact

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -34,6 +34,12 @@ jobs:
         working-directory: contract
         run: pnpm jest --ci --reporters=default --reporters=jest-junit
 
+      - uses: actions/upload-artifact@v4 # upload test results
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: contract-test-results
+          path: ./contract/junit.xml
+
       - name: Publish contract test results
         uses: dorny/test-reporter@v1
         if: success() || failure() # run this step even if previous step failed
@@ -45,6 +51,12 @@ jobs:
       - name: Test web
         working-directory: web
         run: pnpm vitest run --reporter=junit > junit.xml
+
+      - uses: actions/upload-artifact@v4 # upload test results
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: web-test-results
+          path: ./web/junit.xml
 
       - name: Publish web test results
         uses: dorny/test-reporter@v1
